### ISSUE TITLE
rsparcc默认安不上

### ISSUE THREAD

**Issue by lihaicheng7003** [MPBA/r-sparcc#1]
rsparcc 在 cran 好像安不上， 去 github 安装的。
我的安包过程
```r
library(devtools)

install_github("MPBA/r-sparcc")

install.packages("WGCNA")

BiocManager::install("impute")

BiocManager::install("preprocessCore")

install_github("xiaolw95/NetMoss2")
# 终于安装成功
```

**Comment by github-gs** [comment]
i just solve the problem in the same way like you ! maybe you can open an issue in the NetMoss2 repo.

**Comment by lihaicheng7003** [comment]
Thanks, it was my carelessness, my original intention was to open an issue in the NetMoss2 repo
